"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import time

def computeFibonacci(limit):
    ans = 0
    x = 1
    y = 2
    while (x <= limit):
        if (x % 2 == 0):
            ans += x
        x, y = y, x + y

    return ans

if __name__ == "__main__":
    start_time = time.time()
    print(computeFibonacci(limit=4000000))
    print("--- %.10f seconds ---" % (time.time() - start_time))